# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build CI

on:
  push:
    branches:
      - G6T2-16-assign-course-s-to-skill-s

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          # MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: spmg6t2
        ports:
          - 33306:3306

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Create Node Environment 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Package
      run: |
        npm install
    - name: npm build
      run: |
        npm run build
    - name: npm test
      run: |
        npm run test:unit

